apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: cm9vdA==
  mongo-pw: c3VwZXJwdzY0
  mongo-uri: bW9uZ29kYjovL3Jvb3Q6c3VwZXJwdzY0QG1vbmdvLXNlcnZpY2U6MjcwMTcvb25ib2FyZGluZ19ncmFwaHFsX3Rlc3Q/YXV0aFNvdXJjZT1hZG1pbgo=